{
 "title": "Kubernetes / System / Kube-scheduler",
 "description": "Dashboard for kube-scheduler",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "kube-scheduler"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kube Controller Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Has Leader?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "leader_election_master_status{component=\"kube-scheduler\", cluster=~\"$cluster\"} == 1",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kube-scheduler- Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"kube-scheduler\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"kube-scheduler\", cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "REST Client Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(rest_client_requests_total{component=\"kube-scheduler\", cluster=~\"$cluster\"}[5m]) > 0)",
     "legendFormat": "{{method}} ({{code}})"
    }
   ]
  },
  {
   "title": "REST Client Requests (Non 2xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(rest_client_requests_total{component=\"kube-scheduler\", code!~\"2..\", cluster=~\"$cluster\"}[5m]) > 0)\n",
     "legendFormat": "{{method}} ({{code}})"
    }
   ]
  },
  {
   "title": "Controller Manager Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (increase(workqueue_work_duration_seconds_bucket{component=\"kube-scheduler\", cluster=~\"$cluster\"}[5m]) > 0)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Controller Manager Adds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (increase(workqueue_adds_total{component=\"kube-scheduler\", cluster=~\"$cluster\"}[5m]) > 0)\r\n",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}